
language: node_js

node_js:
  - "node"

before_install:
  - rm -fr node_modules
  - npm install
  - npm install jshint terser
  - jshint --version
  - terser --version
  - npm install yargs clear inquirer fuzzy
  - npm install async rimraf commander winston@2.4.5
  - sudo apt-get -y install jq
  - jq --version

script:
  - npm run test-source1
  - npm run test-wepsim-node1
  - npm run test-wepsim-node2

