
language: node_js

node_js:
  - "node"

before_install:
  - npm install jshint
  - jshint --version
  - npm install terser
  - terser --version
  - mkdir -p ~/bin && curl -sSL -o ~/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && chmod +x ~/bin/jq
  - export PATH=$PATH:~/bin
  - jq --version

script:
  - npm run test-source1
  - npm run test-wepsim-node1
  - npm run test-wepsim-node2

