
language: node_js

node_js:
  - "node"

before_install:
  - sudo apt-get -y install jq
  - jshint --version
  - terser --version
  - jq --version

script:
  - npm run test-source1
  - npm run test-wepsim-node1
  - npm run test-wepsim-node2

